### ISSUE TITLE
[3.1.1]: build fails on iOS: 'ReactNativeAvoidSoftinput-Swift.h' file not found with RN v0.70.7

### ISSUE THREAD

**Issue by Lakston** [mateusz1913/react-native-avoid-softinput#143]
### Environment

Library version: 3.1.1
OS version: iOS 15,5  simulator 
react native version : 0.70.7

Hermes and fabric are disabled.

I can build with version: ^3.0.3 and react native 0.70.5 but when updating react native my build fails so I also updated this library just to be sure and it still won't build.

I cleaned my node modules, build folder, derived data, everything I could think of.

### Affected platforms

- [ ] Android
- [X] iOS

### Current behavior

Build fails with `'ReactNativeAvoidSoftinput-Swift.h' file not found`

BaseAvoidSoftInputEvent.mm imports "ReactNativeAvoidSoftinput-Swift.h" 

### Expected behavior

it should build

### Reproduction

none

**Comment by mateusz1913** [comment]
👋 @Lakston could you provide reproducible repo?

**Comment by AlekseyP18** [comment]
The same problem in IOS

"react-native": "0.71.1"

After adding this package I did
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
rm -rf ~/Library/Developer/Xcode/DerivedData/*
pod deintegrate
pod setup
pod install

But it still doesn't work

**Comment by mateusz1913** [comment]
Hi @AlekseyP18 could you provide reproduction repo?

**Comment by Lakston** [comment]
I'll try to make a repo next week if I can, I won't have time this week !

**Comment by mateusz1913** [comment]
@AlekseyP18 @Lakston fix for your issue is available in v3.1.3 🚀

**Comment by AlekseyP18** [comment]
Thank you for you quickly fix!)

**Comment by Lakston** [comment]
Just confirming it works with RN v0.70.7 and v3.1.3, thanks mate !
