### ISSUE TITLE
Whole screen slides down when keyboard is dismissed in iOS

### ISSUE THREAD

**Issue by talhauzair-28** [mateusz1913/react-native-avoid-softinput#151]
### Environment

Library version: ^2.4.6
OS version: iPhone 11 iOS 15.5, also faced this issue on many other iOS devices as well

### Affected platforms

- [ ] Android
- [X] iOS

### Current behavior

When keyboard is closed, the whole screen shifts to bottom, the exact height is same as keyboard. 

Please find the attached video: 

https://user-images.githubusercontent.com/13475617/221155199-3524a626-de08-4aa8-91f8-2b0926d0302b.MP4

### Expected behavior

When the keyboard is dismissed, the screen should not be scrolled down. 

### Reproduction

Private repo

**Comment by mateusz1913** [comment]
👋 @talhauzair-28 unfortunately I'm not able to start investigating the issue without a minimal reproduction repository (I see incorrect behavior on the video, but it doesn't tell me how you use this module and with which UI elements it may interact).

Please do not put "private repo" in the reproduction link field, but instead take your time, and prepare a minimal example on github/gitlab/etc. showcasing the error and link it into the issue description - this is the only way for me, to properly investigate if/why the incorrect behavior is happening

**Comment by mateusz1913** [comment]
Closing as there's no repro provided
