### ISSUE TITLE
Not working on ios

### ISSUE THREAD

**Issue by NadeemKhanFh** [mateusz1913/react-native-avoid-softinput#153]
### Environment

Library version: 3.1.4

### Affected platforms

- [ ] Android
- [X] iOS

### Current behavior

![Simulator Screen Shot - iPhone 14 Pro Max - 2023-03-15 at 15 05 19](https://user-images.githubusercontent.com/124039561/225277582-dd38babc-8e52-497e-9e6c-c7d2cdf40faf.png)

### Expected behavior

It should expand the view

### Reproduction

no

**Comment by NadeemKhanFh** [comment]
its just happening on import { AvoidSoftInputView } from "react-native-avoid-softinput";
its working with import { AvoidSoftInput } from "react-native-avoid-softinput";

**Comment by msageryd** [comment]
I'm getting the exact same error.
*AvoidSoftInputView* works great. But as soon as I give it a function in the onSoftInputHeightChange I get the error.

The same concept works fine in a functional component with `useSoftInputHeightChanged` instead of `onSoftInputHeightChange`.

This works fine: 
```
    render() {
      return (
      <SafeAreaView>
        <AvoidSoftInputView
          style={{flex: 1}}>
            <ScrollView
              ...
           </ScrollView>
         </AvoidSoftInputView
      <SafeAreaView>)
```
This craches:
```
    onSoftInputHeightChange(e) {
        console.log(e);
      }

    render() {
      return (
      <SafeAreaView>
        <AvoidSoftInputView
          onSoftInputHeightChange={this.onSoftInputHeightChange}
          style={{flex: 1}}>
            <ScrollView
              ...
           </ScrollView>
         </AvoidSoftInputView
      <SafeAreaView>)
```

**Comment by msageryd** [comment]
I worked around this for now but not using onSoftInputHeightChange at all. I really whish for this bug to be fixed so I can clean up my code.

I'll leave the alernative solution here if anyone else gets stuck on this.

```
import {Keyboard} from 'react-native';

...

  componentDidMount = () => {
    this.keyboardChangeFrameListener = Keyboard.addListener(
      'keyboardWillChangeFrame',
      ({endCoordinates}) => {
        this.setState({keyboardHeight: endCoordinates.height});
      },
    );

    this.keyboardHideListener = Keyboard.addListener('keyboardDidHide', () => {
      this.setState({keyboardHeight: 0});
    });
  };

  componentWillUnmount = () => {
    this.keyboardChangeFrameListener.remove();
    this.keyboardHideListener.remove();
  };
```

**Comment by msageryd** [comment]
Thanks for pointing this out. It’s been a long time since I worked with class components. 

Initially I created the function with fat arrow. Such functions are automatically bound, aren’t they?

**Comment by msageryd** [comment]
I have now done more testing.
No mather if I bind it manually in the constructor or use an arrow function, the error occurs.
