### ISSUE TITLE
[Android] Sticky Footer gets extra padding when form has many inputs

### ISSUE THREAD

**Issue by jnowakow** [mateusz1913/react-native-avoid-softinput#155]
### Environment

Library version: 3.1.5
OS version: Pixel 4a - Android 13

### Affected platforms

- [X] Android
- [ ] iOS

### Current behavior

When last (or one of the last) input is focused extra space is added under the sticky footer. Please see attached video. When you focus other element is aligns to position where is should be. 

https://user-images.githubusercontent.com/56261019/235115927-f407edd1-096b-4a76-a99c-36b4b119d23d.mp4

To reproduce add few Inputs in `StickyFooterExample` like:
```
...
return (
    <SafeAreaView
      edges={[ 'left', 'right', 'bottom' ]}
      style={commonStyles.screenContainer}
    >
      <View style={styles.scrollWrapper}>
        <ScrollView
          contentContainerStyle={styles.scrollContainer}
          contentInsetAdjustmentBehavior="always"
        >
          <SingleInput />
          <SingleInput />
          <SingleInput />
          <SingleInput />
          <SingleInput />
          <SingleInput />
        </ScrollView>
      </View>
      <Animated.View
        style={[ buttonContainerAnimatedStyle, styles.ctaButtonWrapper ]}
      >
        <View style={styles.ctaButtonContainer}>
          <Button onPress={NOOP} title="Submit" />
        </View>
      </Animated.View>
    </SafeAreaView>
  );
```

### Expected behavior

No extra space should be added no matter which input is focused. It should behave like on ios: 

https://user-images.githubusercontent.com/56261019/235116995-a8365115-65d0-44d0-bf52-ae7f70c7ed59.mov

### Reproduction

https://github.com/mateusz1913/react-native-avoid-softinput/blob/main/packages/app/src/screens/StickyFooterExample.tsx

**Comment by jnowakow** [comment]
I forgot to mention that in issue description but all in all this library looks great!

**Comment by mateusz1913** [comment]
Hi @jnowakow, thx for raising the issue, I'll try to look into it at the weekend.

**Comment by mogelbrod** [comment]
I've been struggling with this exact issue using the regular react-native `<KeyboardAvoidingView>` component for a day now without success. The easiest repro I've found is to render two separate `<TextInput>` fields, one far up in a ScrollView and one further down. Focusing a TextInput that is currently rendered below the area which the keyboard will take up seems to cause android to add additional vertical space that appears to correspond to the delta between the start and end coordinates.

I'll add another example showcasing this in case it might help - note however that this doesn't use `react-native-avoid-softinput` but instead the native components. Light green is the `<KeyboardAvoidingView>`, grey voxes are `<TextInput>`s, red box is meant to be a sticky container (for example a button).

https://user-images.githubusercontent.com/150084/235899571-38b006fa-496b-474c-bfd1-c7b14f8cfd2c.mov

Corresponding code:
```tsx
export default function App() {
  return (
    <KeyboardAvoidingView
      enabled
      behavior={Platform.OS === 'ios' ? 'padding' : 'padding'} // also tried `undefined`/`height` for android, where the extra space isn't added but the red box also doesn't stick
      style={{ flexGrow: 1, backgroundColor: 'rgba(0, 255, 0, 0.2)' }}
    >
      <ScrollView
        style={{
          flex: 1,
          backgroundColor: 'white',
        }}
        contentContainerStyle={{
          flexGrow: 1,
          flexShrink: 0,
          justifyContent: 'center',
        }}
      >
        <SafeAreaView style={{ flexGrow: 1 }}>
          <TextInput style={{ backgroundColor: '#ddd' }} />
          <Spacer multiplier={5} />
          <TextInput style={{ backgroundColor: '#ddd' }} />
          <Spacer multiplier={15} />
          <TextInput style={{ backgroundColor: '#ddd' }} />
          <Spacer multiplier={5} />
          <TextInput style={{ backgroundColor: '#ddd' }} />
        </SafeAreaView>
      </ScrollView>
      <View style={{ height: 40, backgroundColor: 'red' }} />
    </KeyboardAvoidingView>
  )
}
```

**Comment by mateusz1913** [comment]
👋 @mogelbrod thx for your input, "adjustPan" behavior might be the thing that breaks it, I need to double-check it, but in case it's breaking, I'll definitely specify it in library's  installation steps.

@jnowakow do you use "adjustPan" or "adjustResize" in your use case?

**Comment by mateusz1913** [comment]
@jnowakow I tried to reproduce the issue in the example app and I managed to do that, but only when setting `androidWindowSoftInputMode="adjustPan"` (in the below recording I am changing that value at runtime from "adjustResize" to "adjustPan")

https://user-images.githubusercontent.com/25980166/236304689-d3a3a8ab-9116-45fb-a9b4-3251850cb3b0.mp4

I made documentation improvements based on @mogelbrod input, which mention [changing the `androidWindowSoftInputMode` attribute](https://mateusz1913.github.io/react-native-avoid-softinput/docs/guides#keyboard-handling-on-android)

Let me know, if it fixes incorrect behavior in your case

**Comment by jnowakow** [comment]
@mateusz1913 sorry for late response - I was offline for the time. 
It seems that indeed `windowSoftInputMode="adjustPan"` was the problem. Thanks for help!
