### ISSUE TITLE
`setShouldMimicIOSBehavior` view scrolled even though it is not needed (android)

### ISSUE THREAD

**Issue by bryanltobing** [mateusz1913/react-native-avoid-softinput#175]
### Environment

Library version: 4.0.0
OS version: Android 13 Google Pixel 3A Emulator, Physical Device Realme Narzo 30A Android 11

### Affected platforms

- [X] Android
- [ ] iOS

### Current behavior

The view is being scrolled even though the input is not going to be covered by the keyboard when it opens.

https://github.com/mateusz1913/react-native-avoid-softinput/assets/46083126/6d6c3f35-c1f4-460d-871f-e607e783a9c9

### Expected behavior

Should correctly mimic the behavior on ios where the view scrolling only when it is needed

https://github.com/mateusz1913/react-native-avoid-softinput/assets/46083126/5792b992-dca5-456d-8ba5-b1fd071d370c

### Reproduction

https://gist.github.com/bryanltobing/40138ad7fb486d804c46e7631239dee2

**Comment by mateusz1913** [comment]
👋 @bryanltobing thx for reporting the bug, it's fixed in new version 4.0.1 🥳 🚀
