### ISSUE TITLE
Auto adjust on orientation change

### ISSUE THREAD

**Issue by faljabi** [mateusz1913/react-native-avoid-softinput#180]
### Feature request

Hi,

I have question or maybe requesting a feature if it is not there. I am enabling the module only when the user changes the device orientation to landscape using the below code. The issue is if the user was on portrait mode and clicked one of the two inputs say (username and password) and then changes the to landscape, I don't see any padding the keyboard still covering the inputs. I noticed that the view is not enabled until I dismiss the keyboard and open it again. I understand that the library is listening to keyboard events maybe thats why it did not auto adjust the view when orientation changes while the keyboard was already in view.

Is there a method or a way to readjust the view without the hack (dismissing the keyboard on orientation change) ?

`const onFocusEffect = useCallback(() => {

        if (isLandscapeSync()) {

            AvoidSoftInput.setAvoidOffset(-34);
            AvoidSoftInput.setShouldMimicIOSBehavior(true);
            AvoidSoftInput.setEnabled(true);
        }

        return () => {

            AvoidSoftInput.setShouldMimicIOSBehavior(false);
            AvoidSoftInput.setEnabled(false);

            Keyboard.dismiss(); // I don't like this hack.
        };

    }, [isLandscapeSync()]);`

Thanks for the amazing library.

**Comment by mateusz1913** [comment]
Hi @faljabi, is that happening on both platforms or only one of them?

I think that in principle, the keyboard events **_should_** be fired by the operating system whenever device orientation changes, but I wonder if it's sth dependent on the platform. And if the events are fired, then the library should handle it correctly. If that's not the case, then I guess it would be hard to get the proper keyboard offset values

Tbh, I don't see a tidy way of implementing what you described, if it's not backed by the correct keyboard offset values taken from keyboard events

**Comment by faljabi** [comment]
I just tried it on both platforms (Physical iPhone and Android (Emulator). Both behaving the same. Anyway I do not use that isLandscapeSync flag anymore and I enable the module anyway which is already adds padding only when keyboards covers the inputs. So that flag was really a bit more defensive.

Thank you for your quick response.

**Comment by mateusz1913** [comment]
Thx @faljabi, I'll close in that case
