### ISSUE TITLE
Android Screen view pushed up on keyboard opening.

### ISSUE THREAD

**Issue by saadi-ninjasCode** [mateusz1913/react-native-avoid-softinput#192]
### Environment

Library version: 4.0.1
OS version: Android
**Other Packages:** 
"react-native": "0.72.5",
"@react-navigation/native": "^6.1.7",
"@react-navigation/stack": "^6.3.17",

### Affected platforms

- [x] Android
- [ ] iOS

### Current behavior

I have observed that when I focus on the input present in the header of an Android device, the screen view is pushed up and the text input hides behind the status bar. I have attached a video below for reference. 

I am using the same codebase present in the example folder (_react-native-avoid-softinput/packages/app/src/screens/FormExample.tsx_) and have made the following changes: 

- I added **TextInput** in the React-Navigation Header. 
- Whenever I focus on the TextInput, the Android screen view is pushed upward and textinput hides behind the status bar.

However, this behavior seems laggy and jerky.

https://github.com/mateusz1913/react-native-avoid-softinput/assets/57723965/ec749b8e-1c46-456d-b718-4d3bc7aba402

### Expected behavior

Android Screen view should not be pushed upward. 
There will be no laggy and jerky behavior.

### Reproduction

Add the follwing code in **FormExample.tsx**

```
const navigation = useNavigation();
  const { top } = useSafeAreaInsets();
  React.useEffect(() => {
    navigation.setOptions({
      header: () => (
        <View
          style={{
            marginTop: top,
            justifyContent: "center",
            backgroundColor: "#FFEE",
          }}
        >
          <TextInput style={{ borderWidth: 2 }} placeholder="Header Input" />
        </View>
      ),
    });
  }, []);
```

**Comment by mateusz1913** [comment]
Hey @saadi-ninjasCode, thx reporting the issue! It's fixed and released in v4.0.2 🥳
