### ISSUE TITLE
Android Screen Content Overlaps with Status Bar

### ISSUE THREAD

**Issue by hamzamekk** [mateusz1913/react-native-avoid-softinput#197]
### Environment

Library version: 4.0.1
OS version: Samsung A52 android 13 

### Affected platforms

- [X] Android
- [ ] iOS

### Current behavior

while I was working on one of my apps I noticed after using the [module usage](https://mateusz1913.github.io/react-native-avoid-softinput/docs/guides/usage-module) my screen is pushed under the status bar without any reason

![403406398_736993721127850_6078853094677895465_n](https://github.com/mateusz1913/react-native-avoid-softinput/assets/34113375/89008c96-7e69-4e4c-a232-6a9c560d3c07)

### Expected behavior

when I remove the code of soft input it turns right the screen is now under the status bar

![WhatsApp Image 2023-12-09 at 19 14 01](https://github.com/mateusz1913/react-native-avoid-softinput/assets/34113375/6f4538f6-973f-421d-9587-216f94fe408d)

### Reproduction

in my code there is nothing special 

a navigation file

```
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import * as React from 'react';

import { PersonalInformation } from '@/screens';

export type AppStackParamList = {
  TabNavigator: undefined;
  PersonalInformation: undefined;
};

const Stack = createNativeStackNavigator<AppStackParamList>();

export const AppNavigator = () => {
  return (
    <Stack.Navigator
      screenOptions={{
        headerShown: false,
        gestureEnabled: false,
        animation: 'none',
      }}
      // initialRouteName="TabNavigator"
    >
      {/* <Stack.Screen name="TabNavigator" component={TabNavigator} /> */}
      <Stack.Screen
        name="PersonalInformation"
        component={PersonalInformation}
      />
    </Stack.Navigator>
  );
};
```

and my screen 
```
import * as React from 'react';

import { useSoftKeyboardEffect } from '@/core';
import { FocusAwareStatusBar, Header, Input } from '@/ui';

export const PersonalInformation = () => {
  useSoftKeyboardEffect();

  return (
    <>
      <FocusAwareStatusBar />
      <Header title="Personal Information" backIcon />
      <Input label="test" />
    </>
  );
};

```

and my useSoftKeyboardEffect function 

```
import { useFocusEffect } from '@react-navigation/native';
import { AvoidSoftInput } from 'react-native-avoid-softinput';

/**
 *  This hook should be used in every screen that has a form input field to avoid the keyboard
 *  This is not a one for all solution, if you want more customization please refer to those examples: https://mateusz1913.github.io/react-native-avoid-softinput/docs/recipes/recipes-form
 */

export const useSoftKeyboardEffect = () => {
  useFocusEffect(() => {
    AvoidSoftInput.setShouldMimicIOSBehavior(true);
    AvoidSoftInput.setEnabled(true);
    // AvoidSoftInput.setAvoidOffset(30);
    AvoidSoftInput.setShowAnimationDelay(0);
    AvoidSoftInput.setShowAnimationDuration(150);
    AvoidSoftInput.setHideAnimationDuration(150);
    AvoidSoftInput.setHideAnimationDelay(0);
    return () => {
      AvoidSoftInput.setAvoidOffset(0);
      AvoidSoftInput.setEnabled(false);
      AvoidSoftInput.setShouldMimicIOSBehavior(false);
    };
  });
};

```

**Comment by mateusz1913** [comment]
Hi @hamzamekk, pls put proper link to reproduction repository. Without it I'm not able to investigate the issue and help you

**Comment by hamzamekk** [comment]
@mateusz1913 here is the link repo https://github.com/hamzamekk/quoteecho i've edited everything so you can go directly to the screen where the issue is, my project is based on this template https://github.com/obytes/react-native-template-obytes

**Comment by mateusz1913** [comment]
thx, will take a look

**Comment by hamzamekk** [comment]
@mateusz1913 thank you for your time

**Comment by mateusz1913** [comment]
@hamzamekk before I dig depper I want to ask: is the screen that is mentioned in the screenshot using SafeAreaView (from react-native-safe-area-context)?

The reason I am asking is that the module usage (in your app via custom useSoftKeyboardEffect hook) on android makes the app being drawn behind system bars (on android its called edge-to-edge mode). This is done to align it with the ios (where by default everything is rendered behind system top and bottom bars). In such cases it's recommended to wrap displayed UI in SafeAreaView (same like it's done for ios).

If that screen is not wrapped in SafeAreaView, try to wrap it and maybe it will work just fine. If it won't, let me know and I'll try to investigate it

**Comment by hamzamekk** [comment]
@mateusz1913 thank you, now it's working, I was using safeAriaView from here [here](https://github.com/obytes/react-native-template-obytes/blob/master/src/ui/core/view.tsx) and now after switching it working fine

**Comment by hamzamekk** [comment]
🚀  🚀  🚀 
 
 sure ill check with the owner, thank you

**Comment by leotj** [comment]
Hi @hamzamekk how did you fix the issue?
I'm still facing the same issue even though I've used SafeAreaView from react-native-safe-area-context

**Comment by hamzamekk** [comment]
> Hi @hamzamekk how did you fix the issue?
> I'm still facing the same issue even though I've used SafeAreaView from react-native-safe-area-context

Hi, every screen i need the keyboard i use this hook 
const insets = useSafeAreaInsets()
To add top margin equal insets.top
