### ISSUE TITLE
 Bug sticky footer component is hidden under keyboard on nexus_s device

### ISSUE THREAD

**Issue by IvanIhnatsiuk** [mateusz1913/react-native-avoid-softinput#37]
# Bug
## Description

Hi, @mateusz1913! 

I ran the example app on the device and noticed that on nexus_s sticky footer is below the keyboard, but on other emulators this component is above the keyboard

## Steps to reproduce
1. run example app on nexus_s device API 29
2. open sticky footer example 
3. See that sticky footer is under the keyboard

## Video

https://user-images.githubusercontent.com/86000012/158026343-e7a53f54-e379-4228-8063-68f4a37d3d93.mov

**Comment by mateusz1913** [comment]
Thanks @IvanIhnatsiuk , navigation bar height was subtracted, even though, it's not displayed inside screen.
