### ISSUE TITLE
Keyboard not avoiding when new lines are added (multiline input)

### ISSUE THREAD

**Issue by ggunti** [mateusz1913/react-native-avoid-softinput#44]
### Environment

Library version: 2.3.3
OS version: iPhone 12, iOS 14.5

### Affected platforms

- [ ] Android
- [X] iOS

### Current behavior

It does not avoid the keyboard when new lines are added (multiline input).
Please check the video below:

https://user-images.githubusercontent.com/26307699/159251978-13afd732-b88b-44e8-9ff7-043990e93165.mov

### Expected behavior

Scroll down when new line is added to the input component

### Reproduction

I wrap my page components into:
```
const KeyboardAvoiding = props => {
  return (
    <AvoidSoftInputView
      avoidOffset={100}
      easing='easeIn'
      hideAnimationDelay={100}
      hideAnimationDuration={300}
      showAnimationDelay={100}
      showAnimationDuration={800}
      style={styles.container}
    >
      {props.children}
    </AvoidSoftInputView>
  );
};
```

**Comment by mateusz1913** [comment]
Hi @ggunti , this library (both `AvoidSoftInput` module and `AvoidSoftInputView` component) relies on keyboard frame events. That means, applied padding/translation will not change **_unless there is some keyboard frame event_** (either keyboard hides or is about to be displayed).
I would recommend to wrap your content form in a scroll view, which will make your multiline input fully accessible even if you add new lines

Simplified example:
```ts
const KeyboardAvoiding = props => {
  return (
    <AvoidSoftInputView
      avoidOffset={100}
      easing='easeIn'
      hideAnimationDelay={100}
      hideAnimationDuration={300}
      showAnimationDelay={100}
      showAnimationDuration={800}
      style={styles.container}
    >
      {props.children} 
    </AvoidSoftInputView>
  );
};

const Form = props => {
  return (
    <ScrollView> // <--- wrap form content with scroll view
      // ... your form
    </ScrollView>
  )
}

const App = props => {
  return (
    // ...
    <KeyboardAvoiding>
      <Form /> // <------------ your form 
    </KeyboardAvoiding>
    // ...
  )
}
```
