### ISSUE TITLE
Space is not hidden after typing values on the field

### ISSUE THREAD

**Issue by IvanIhnatsiuk** [mateusz1913/react-native-avoid-softinput#47]
### Environment

Hi @mateusz1913! It's again me. Sorry to come off like this, but I found a bug :(

Library version: 2.4.0
OS version: 

Android 7 nexus 5 

Android 10 nexus S

### Affected platforms

- [X] Android
- [ ] iOS

### Current behavior

When I'm entering values and after that press on `done` button keyboard avoid space is not hidden, but if I'm pressing outside and blur event was happened on input it works as expected.

### Expected behavior

Keyboard avoid space should be hidden after pressing on keyboard done button

### Reproduction

1. run example app
2. go to form screen
3. type any value on the last input
4. press done on the keyboard
5. see that space is not hidden

when press on keyboard done button:

https://user-images.githubusercontent.com/86000012/160002483-8238ea44-78fa-4ad0-9c1a-c1e8f6227137.mov

https://user-images.githubusercontent.com/86000012/160002492-c184e811-ebfd-48d2-af4b-2aaa009da8a6.mov

blur when press outside: 

https://user-images.githubusercontent.com/86000012/160002599-de553e47-84f4-4b90-8a0c-fb804348dc30.mov

**Comment by mateusz1913** [comment]
Hi @IvanIhnatsiuk , the issue is weird cause I can only reproduce it, when interacting with physical keyboard. When I only soft keyboard inside emulator, it works as expected

**Comment by mateusz1913** [comment]
Thx @IvanIhnatsiuk  for submitting that issue, it is resolved and released with version 2.4.1 🎉
