### ISSUE TITLE
`enabled` prop for `AvoidSoftInputView`

### ISSUE THREAD

**Issue by mateusz1913** [mateusz1913/react-native-avoid-softinput#50]
### Feature request

`AvoidSoftInputView` can have `enabled` prop to control if component should handle keyboard events.
It can be useful to disable component and treat it as a simple `View` when condition is not satisfied.
It should handle case when `enabled` value is changed, when keyboard is visible:
- when value changes to `true` AND later keyboard is dismissed - it should ignore "remove offset" event (because there is nothing to be removed)
- when value changes to `false` AND later keyboard is dismissed - it should still "remove offset" because we do not want to leave blank space

**Comment by a-eid** [comment]
that would be very useful, thank you.
