### ISSUE TITLE
Support "New Architecture"

### ISSUE THREAD

**Issue by mateusz1913** [mateusz1913/react-native-avoid-softinput#51]
### Feature request

Start "New Architecture" migration when ~~react-native v0.68 will be stable~~ all "New Architecture" features (Swift/Kotlin support, autolinking, etc.) will be _**stable-ish**_

**Comment by mateusz1913** [comment]
AFAIK, it's possible from v0.69. With samples, I don't know if offical one has Kotlin or Swift example (probably only Java + Objective-C++)

**Comment by PritishSawant** [comment]
thanks but this video says its not possible to use swift

https://www.youtube.com/watch?v=_I6bH5_rO2k

Will it be possible for you to help me in case I create a sample repo with swift and new architecture?

**Comment by PritishSawant** [comment]
Use bridging for swift support
