### ISSUE TITLE
extra space at the bottom when the keyboard is up for both android & ios.

### ISSUE THREAD

**Issue by a-eid** [mateusz1913/react-native-avoid-softinput#53]
### Environment

Library version: ^2.4.1
OS version: iPhone 13, iOS 15.0

```bash
System:
    OS: macOS 11.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
    Memory: 25.16 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 8.3.1 - ~/n/bin/npm
    Watchman: 2022.02.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/ahmedelshentenawy/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: 20.1.5948944
  IDEs:
    Android Studio: Bumblebee 2021.1.1 Patch 1 Bumblebee 2021.1.1 Patch 1
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
 ```

### Affected platforms

- [X] Android
- [X] iOS

### Current behavior

extra space at the bottom when the keyboard is up.

### Expected behavior

there should be no extra space.

### Reproduction

https://user-images.githubusercontent.com/19273413/161309082-29617cf4-a295-4a78-90ce-d3d94b05f527.mp4

https://user-images.githubusercontent.com/19273413/161309186-9c30026b-7d32-4114-991c-f8e2337896c9.mp4

```ts
 // using the native-stack from RN screens.
  React.useEffect(
    () => {
      const unsubscribe = navigation.addListener('appear', e => {
        AvoidSoftInput.setEnabled(true)
      });

      return () => {
        AvoidSoftInput.setEnabled(false)
        unsubscribe();
      };
    },
    [navigation]
  );
```

**Comment by mateusz1913** [comment]
Hi @a-eid , could you provide a link to reproduction repo, so I can investigate it?

**Comment by a-eid** [comment]
@mateusz1913 hey, thank you for the awesome lib, will post a repro link later today/tomorrow.

**Comment by a-eid** [comment]
Seems that I posted the wrong video 😅

**Comment by mateusz1913** [comment]
@a-eid thx for providing videos. As **workaround** I can recommend using `AvoidInput.setAvoidOffset` method with negative value, so you can eliminate that extra space. However, I am looking forward for a separate reproduction repo, so I will be able to investigate it in isolated environment

**Comment by a-eid** [comment]
@mateusz1913 I'll close this since upgrading to latest version fixed the issue for me somehow on both ios and andorid.
