### ISSUE TITLE
Unable to build with EAS on Expo SDK 46

### ISSUE THREAD

**Issue by Randall71** [mateusz1913/react-native-avoid-softinput#88]
### Environment

Library version: 2.4.6
eas-cli: 2.1.0
Expo SDK: 46.0.10
Workflow: Managed

### Affected platforms

- [x] Android
- [ ] iOS

### Current behavior

When I decide to build my app with EAS Build for Android I get this. I think this error comes from the Kotlin version and all the errors I get point to this package. I really hope I'm not wrong.

![Capture d’écran (204)](https://user-images.githubusercontent.com/51382079/189719719-b73b76ad-2a97-449c-8389-1951faf76269.png)

### Expected behavior

I expect that the build will success like on IOS 

### Reproduction

I think install this package on an Expo managed App wth SDK 46 and build it will create the same result on Android

**Comment by Randall71** [comment]
I add an `expo-build-properties` to specify KotlinVersion to 1.6.10 and build pass

**Comment by mateusz1913** [comment]
Hi @Randall71, thx for submitting an issue. Technically it's not a bug, but rather project setup problem.

However, I think it's worth to include some information on how to troubleshoot such error and especially when it can happen on both conventional RN projects and those with expo/EAS builds.

I think it would be great to add it inside `docs/docs/guides/INSTALLATION.mdx`. There, it could explain how to specify kotlinVersion with `expo-build-properties` and how to do it in conventional RN project (in `android/build.gradle` inside buildscript block like it's done in the example app).

Would you want to contribute to the docs on how to tackle such errors?

**Comment by Randall71** [comment]
Thanks for your quick response. 
Yes, I'm definitely open to adding this section to help people easily get started with this great library you've created.
